<?php
/**
 * UUPD licensing + UUPD updater bootstrap for a THEME (UUPD provider)
 * Slug:  uupd-test-theme
 * Server: https://uupdserver.wpcode.dev
 * Item: 23
 *
 * Requires these files in your theme:
 *   /uupd/updater.php
 *   /uupd/class-uupd-license-ui.php
 */

defined('ABSPATH') || exit;

/// Generated by UUPD Theme Bootloader Generator
// Source provider: WSL

// ---- Config ----
define( 'UUPD_EXAMPLE_THEME_VENDOR', 'tdlab' );
define( 'UUPD_EXAMPLE_THEME_SLUG', 'example-theme' );
define( 'UUPD_EXAMPLE_THEME_NAME', 'Example Theme' );
define( 'UUPD_EXAMPLE_THEME_SERVER', 'https://wsl.tdlab.uk' ); // no trailing / needed
define( 'UUPD_EXAMPLE_THEME_ITEM_ID', 33 );

/**
 * Optional debug
 */
// add_filter( 'updater_enable_debug', '__return_true' );

function example_plugin_require_file( $relative_path ) {
    $path = trailingslashit( get_stylesheet_directory() ) . ltrim( $relative_path, '/' );
    if ( file_exists( $path ) ) {
        require_once $path;
        return true;
    }
    return false;
}

/**
 * 1) Register the UUPD License UI instance EARLY (admin only).
 *    This is important for wp-config constant auto-activation so the key
 *    is available before the updater fetches metadata.
 *
 * NOTE: after_setup_theme runs before init.
 */
add_action( 'after_setup_theme', function() {
    if ( ! is_admin() ) {
        return;
    }

    if ( ! example_plugin_require_file( '/uupd/class-uupd-license-ui.php' ) ) {
        return;
    }

    if ( ! class_exists( '\\UUPD\\UI\\License\\V1\\UUPD_License_UI' ) ) {
        return;
    }

    $theme   = wp_get_theme();
    $version = $theme->get( 'Version' ) ?: '0.0.0';

    \UUPD\UI\License\V1\UUPD_License_UI::register( [
        'vendor'           => UUPD_RUP_EXAMPLE_PLUGIN_VENDOR,
        'slug'             => UUPD_RUP_EXAMPLE_PLUGIN_SLUG,
        'item_id'          => UUPD_RUP_EXAMPLE_PLUGIN_ITEM_ID,
        'plugin_name'      => UUPD_RUP_EXAMPLE_PLUGIN_NAME,
        'license_server'   => UUPD_RUP_EXAMPLE_PLUGIN_SERVER,
        'metadata_base'    => UUPD_RUP_EXAMPLE_PLUGIN_SERVER,
        'license_provider' => 'uupd',
        'current_version'  => $version,
        'menu_parent'      => false,
        'menu_slug'        => 'uupd-example-plugin-licence',
    ] );
}, 1 );

/**
 * 2) Register the updater (theme updates) AFTER the UI has registered its filters.
 */
add_action( 'after_setup_theme', function() {
    if ( ! example_plugin_require_file( '/uupd/updater.php' ) ) {
        return;
    }

    $theme   = wp_get_theme();
    $version = $theme->get( 'Version' ) ?: '0.0.0';

    if ( class_exists( '\\UUPD\\V2\\UUPD_Updater_V2' ) ) {
        \UUPD\V2\UUPD_Updater_V2::register( [
            'vendor'           => UUPD_RUP_EXAMPLE_PLUGIN_VENDOR,
            'slug'             => UUPD_RUP_EXAMPLE_PLUGIN_SLUG,
            'real_slug'        => UUPD_RUP_EXAMPLE_PLUGIN_SLUG,
            'name'             => UUPD_RUP_EXAMPLE_PLUGIN_NAME,
            'version'          => $version,
            'server'           => UUPD_RUP_EXAMPLE_PLUGIN_SERVER,
            'allow_prerelease' => (bool) get_option( 'uupd_example_plugin_allow_prerelease', false ),
        ] );
    }
}, 5 );

/**
 * 3) Apply prerelease option instantly (vendor-aware)
 */
add_filter(
    'uupd/allow_prerelease/' . UUPD_RUP_EXAMPLE_PLUGIN_VENDOR . '/' . UUPD_RUP_EXAMPLE_PLUGIN_SLUG,
    function( $allow, $vendor, $slug ) {
        return (bool) get_option( 'uupd_example_plugin_allow_prerelease', false );
    },
    10,
    3
);

/**
 * 4) Update settings under Appearance → Example Plugin
 */
add_action( 'admin_init', function() {
    register_setting(
        'example_plugin_settings',
        'uupd_example_plugin_allow_prerelease',
        [
            'type'              => 'boolean',
            'sanitize_callback' => static function( $v ) {
                return (int) ! empty( $v );
            },
            'default'           => 0,
        ]
    );

    add_settings_section(
        'example_plugin_updates',
        __( 'Update Settings', 'example-plugin' ),
        '__return_false',
        'uupd-example-plugin-settings'
    );

    add_settings_field(
        'example_plugin_allow_prerelease_field',
        __( 'Allow prereleases', 'example-plugin' ),
        function() {
            $val = (bool) get_option( 'uupd_example_plugin_allow_prerelease', false );
            ?>
            <label>
                <input type="checkbox" name="uupd_example_plugin_allow_prerelease" value="1" <?php checked( $val, true ); ?> />
                <?php esc_html_e( 'Enable beta/RC/dev updates', 'example-plugin' ); ?>
            </label>
            <p class="description">
                <?php esc_html_e( 'When enabled, the updater will offer pre-release versions (alpha, beta, RC, dev).', 'example-plugin' ); ?>
            </p>
            <?php
        },
        'uupd-example-plugin-settings',
        'example_plugin_updates'
    );
} );

add_action( 'admin_menu', function() {
    add_theme_page(
        __( 'Example Plugin', 'example-plugin' ),
        __( 'Example Plugin', 'example-plugin' ),
        'edit_theme_options',
        'uupd-example-plugin-settings',
        'example_plugin_render_settings_page'
    );
} );

function example_plugin_render_settings_page() {
    if ( ! current_user_can( 'edit_theme_options' ) ) {
        return;
    }

    $slug      = UUPD_RUP_EXAMPLE_PLUGIN_SLUG;
    $nonce     = wp_create_nonce( 'uupd_manual_check_' . $slug );
    $check_url = admin_url(
        sprintf(
            'admin.php?action=uupd_manual_check&slug=%s&_wpnonce=%s',
            rawurlencode( $slug ),
            $nonce
        )
    );
    ?>
    <div class="wrap">
        <h1><?php echo esc_html( UUPD_RUP_EXAMPLE_PLUGIN_NAME ); ?></h1>

        <form method="post" action="options.php">
            <?php
            settings_fields( 'example_plugin_settings' );
            do_settings_sections( 'uupd-example-plugin-settings' );
            submit_button( __( 'Save Changes', 'example-plugin' ) );
            ?>
        </form>

        <hr />
        <p><?php esc_html_e( 'Need to refresh update data now?', 'example-plugin' ); ?></p>
        <p>
            <a class="button button-secondary" href="<?php echo esc_url( $check_url ); ?>">
                <?php esc_html_e( 'Check for updates now', 'example-plugin' ); ?>
            </a>
        </p>
    </div>
    <?php
}

/**
 * 5) Licensing: Settings → Example Plugin Licence
 */
add_action( 'admin_menu', function() {
    add_options_page(
        __( 'Example Plugin Licence', 'example-plugin' ),
        __( 'Example Plugin Licence', 'example-plugin' ),
        'manage_options',
        'uupd-example-plugin-licence',
        'example_plugin_render_licence_page'
    );
} );

function example_plugin_render_licence_page() {
    if ( ! current_user_can( 'manage_options' ) ) {
        return;
    }

    if ( ! class_exists( '\\UUPD\\UI\\License\\V1\\UUPD_License_UI' ) ) {
        echo '<div class="wrap"><div class="notice notice-error"><p>';
        echo esc_html__( 'License UI class not loaded. Check your bundled UUPD files exist in the active theme.', 'example-plugin' );
        echo '</p></div></div>';
        return;
    }

    $inst = \UUPD\UI\License\V1\UUPD_License_UI::get_instance(
        UUPD_RUP_EXAMPLE_PLUGIN_VENDOR,
        UUPD_RUP_EXAMPLE_PLUGIN_SLUG
    );

    if ( ! $inst ) {
        echo '<div class="wrap"><div class="notice notice-error"><p>';
        echo esc_html__( 'License handler not initialized. Ensure registration is running for admin requests.', 'example-plugin' );
        echo '</p></div></div>';
        return;
    }

    $inst->render_page();
}
